services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: baristaone-backend-prod
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: baristaone-worker-prod
    command: ["node", "workers/orderCreatedWorker.js"]
    env_file:
      - ./backend/.env
    environment:
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: baristaone-frontend-prod
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: baristaone-redis-prod
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: baristaone-rabbitmq-prod
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped